apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: backend
  labels:
    app: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
        - name: backend
          image: 475834860148.dkr.ecr.ap-south-1.amazonaws.com/mern-backend:1.0.0
          ports:
            - containerPort: 5000
